---
title: "Exercise 5"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### What is complex contagion and how it’s different from simple contagion (you may want to refer to readings – Centola)

Simple contagion in a network refers to a process in which each individual in the network becomes infected after a single exposure to another infected individual in the network. In this process, given a single infected node, after every specified period, all nodes adjacent to that node are infected. Simple contagion models can be good models for highly infectious diseases or situations in which the spread of misinformation is likely. 

On the other hand, in complex contagion, multiple sources of exposure are required in order for a given node to be infected. A node exposed to one infected individual will not become infected, instead infection can depend on the total count of exposures as well as other node and network characteristics.

#### What does complex contagion mean for diffusion of behaviors in organization

In an organization, a given behavior, either beneficial or harmful to the wider organization, can spread from employee to employee. If we consider a simple contagion model, a given behavior can spread very easily within an organization, within first exposure (or interaction) with those exhibiting that behavior. In a complex contagion, the spread of certain behavior is more difficult. The spread may depend on interacting with many individuals who exhibit that behavior, individual characteristics (inclination towards persuasion), social and economic factors as well as wider organizational attributes. If a given behavior is desired or unwanted, more effort and resources might be needed to achieve the needed effect. 

#### How can we use the threshold models to better manage: Prosocial behavior in organizations, Learning, Toxic or unproductive behaviors

In the threshold model, a given node is infected or adopts a behavior only if a certain threshold is passed. This threshold is indicative of the critical fraction or number of a given node's connections that have already been infected or have adopted that behavior. 

In an organization, upon calculating this threshold for all individuals, we can estimate the relative persuasiveness and persuadability of those in our organization. If the average threshold is low across the organization, efforts should be more focused on derailing the spread of toxic of unproductive behaviors. For positive behaviors such as prosocial behavior and learning, a low threshold can indicate that these desired behaviors will spread without much difficulty and lower effort might be needed. Alternatively, if the threshold is high, there can be less concern over the spread of harmful behaviors but possibly more effort required to spread beneficial behaviors.

